
--specify that TEST_DB will be used
USE TEST_DB;

--drop TB_CHALLENGE_2_REQUIREMENT_2 table in case it already exists
DROP TABLE IF EXISTS dbo.TB_CHALLENGE_2_REQUIREMENT_2;

--CTE with main data
WITH CTE_MAIN AS (

SELECT
DE.DEPARTMENT DEPARTMENT_NAME
,JB.JOB JOB_NAME

,HE.ID
,HE.NAME EMPLOYEE_NAME
,HE.DATETIME
,HE.DEPARTMENT_ID
,HE.JOB_ID

--converting DATETIME column into a date
,CASE WHEN HE.DATETIME = '0' THEN CAST('1/1/1990' AS DATE) ELSE CAST(LEFT(HE.DATETIME, 10) AS DATE) END HIRED_DATE

--converting date into quarter of the year
,CASE WHEN HE.DATETIME = '0' THEN 'NA' ELSE CONCAT('Q', DATEPART(QUARTER, CAST(LEFT(HE.DATETIME, 10) AS DATE))) END HIRED_QUARTER

FROM HIRED_EMPLOYEES HE

JOIN DEPARTMENTS DE
ON HE.DEPARTMENT_ID = DE.ID

JOIN JOBS JB
ON HE.JOB_ID = JB.ID
)

--CTE for counting the employees per each department, job and quarter
--per request, only data from 2021 is being used as can be seen in the WHERE clause
,CTE_METRIC_COUNT_2021 AS (
SELECT
DEPARTMENT_NAME, JOB_NAME, HIRED_QUARTER
,COUNT(EMPLOYEE_NAME) HIRED_QUARTER_COUNT

FROM CTE_MAIN

WHERE LEFT(HIRED_DATE, 4) = '2021'
GROUP BY DEPARTMENT_NAME, JOB_NAME, HIRED_QUARTER
--ORDER BY DEPARTMENT_NAME, JOB_NAME
)

--getting employees hired in 2021 for all departments
,CTE_METRIC_SUM_2021 AS (
SELECT
DEPARTMENT_NAME
,SUM(HIRED_QUARTER_COUNT) HIRED_QUARTER_SUM
FROM CTE_METRIC_COUNT_2021
GROUP BY DEPARTMENT_NAME
)

--getting average of employees hired in 2021 for all departments
,CTE_METRIC_AVG_2021 AS (
SELECT
AVG(HIRED_QUARTER_SUM) HIRED_QUARTER_AVG
FROM CTE_METRIC_SUM_2021
)

--CTE for departments that hired more employees than [average of employees hired in 2021 for all departments: CTE_METRIC_AVG_2021]
,CTE_CHALLENGE_2 AS (
SELECT
DEPARTMENT_ID
,DEPARTMENT_NAME
,COUNT(DISTINCT EMPLOYEE_NAME) HIRED_QUARTER_COUNT

FROM CTE_MAIN

GROUP BY DEPARTMENT_ID, DEPARTMENT_NAME

--condition for checking if employees hired in a specific department is higher than [average of employees hired in 2021 for all departments: CTE_METRIC_AVG_2021]
HAVING COUNT(DISTINCT EMPLOYEE_NAME) > (SELECT HIRED_QUARTER_AVG FROM CTE_METRIC_AVG_2021)

--ORDER BY HIRED_QUARTER_COUNT DESC
)

--creating TB_CHALLENGE_2_REQUIREMENT_2 table with results for [requirement 2] of [challenge 2]
SELECT
DEPARTMENT_ID, DEPARTMENT_NAME, HIRED_QUARTER_COUNT
INTO dbo.TB_CHALLENGE_2_REQUIREMENT_2
FROM CTE_CHALLENGE_2
ORDER BY HIRED_QUARTER_COUNT DESC;

--query for validating output
--SELECT DEPARTMENT_ID, DEPARTMENT_NAME, HIRED_QUARTER_COUNT
--FROM dbo.TB_CHALLENGE_2_REQUIREMENT_2
--ORDER BY HIRED_QUARTER_COUNT DESC;

