
--specify that TEST_DB will be used
USE TEST_DB;

--drop TB_CHALLENGE_2_REQUIREMENT_1 table in case it already exists
DROP TABLE IF EXISTS dbo.TB_CHALLENGE_2_REQUIREMENT_1;

--CTE with main data
WITH CTE_MAIN AS (

SELECT
DE.DEPARTMENT DEPARTMENT_NAME
,JB.JOB JOB_NAME

,HE.ID
,HE.NAME EMPLOYEE_NAME
,HE.DATETIME
,HE.DEPARTMENT_ID
,HE.JOB_ID

--converting DATETIME column into a date
,CASE WHEN HE.DATETIME = '0' THEN CAST('1/1/1990' AS DATE) ELSE CAST(LEFT(HE.DATETIME, 10) AS DATE) END HIRED_DATE

--converting date into quarter of the year
,CASE WHEN HE.DATETIME = '0' THEN 'NA' ELSE CONCAT('Q', DATEPART(QUARTER, CAST(LEFT(HE.DATETIME, 10) AS DATE))) END HIRED_QUARTER

FROM HIRED_EMPLOYEES HE

JOIN DEPARTMENTS DE
ON HE.DEPARTMENT_ID = DE.ID

JOIN JOBS JB
ON HE.JOB_ID = JB.ID
)

--CTE for counting the employees per each department, job and quarter
--per request, only data from 2021 is being used as can be seen in the WHERE clause
,CTE_SUBRESULT AS (
SELECT
DEPARTMENT_NAME, JOB_NAME, HIRED_QUARTER
,COUNT(EMPLOYEE_NAME) HIRED_QUARTER_COUNT

FROM CTE_MAIN

WHERE LEFT(HIRED_DATE, 4) = '2021'
GROUP BY DEPARTMENT_NAME, JOB_NAME, HIRED_QUARTER
--ORDER BY DEPARTMENT_NAME, JOB_NAME
)

--CTE for creating new columns (Q1, Q2, ...) that will store the total sum of employees per department and job
,CTE_CHALLENGE_1 AS (
SELECT
DEPARTMENT_NAME, JOB_NAME
,SUM(CASE WHEN HIRED_QUARTER = 'Q1' THEN HIRED_QUARTER_COUNT ELSE 0 END) Q1
,SUM(CASE WHEN HIRED_QUARTER = 'Q2' THEN HIRED_QUARTER_COUNT ELSE 0 END) Q2
,SUM(CASE WHEN HIRED_QUARTER = 'Q3' THEN HIRED_QUARTER_COUNT ELSE 0 END) Q3
,SUM(CASE WHEN HIRED_QUARTER = 'Q4' THEN HIRED_QUARTER_COUNT ELSE 0 END) Q4

FROM CTE_SUBRESULT

GROUP BY DEPARTMENT_NAME, JOB_NAME
--ORDER BY DEPARTMENT_NAME, JOB_NAME
)

--creating TB_CHALLENGE_2_REQUIREMENT_1 table with results for [requirement 1] of [challenge 2]
SELECT
DEPARTMENT_NAME, JOB_NAME, Q1, Q2, Q3, Q4
INTO dbo.TB_CHALLENGE_2_REQUIREMENT_1
FROM CTE_CHALLENGE_1
ORDER BY DEPARTMENT_NAME, JOB_NAME;

--query for validating output
--SELECT *
--FROM dbo.TB_CHALLENGE_2_REQUIREMENT_1
--ORDER BY DEPARTMENT_NAME, JOB_NAME;


